### ISSUE TITLE
[detail] route - layout, missing space

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#107]
Missing space on top of download block

![image](https://github.com/teritorio/vido/assets/1785486/053ff24d-b035-4f33-9ad9-1f5384513524)

**Comment by wazolab** [comment]
Is this issue still here ?
It looks ok to me :
![image](https://github.com/teritorio/vido/assets/38253764/c95a5b47-572b-4fbe-b998-a08ec0a5a7a5)
