### ISSUE TITLE
lost display of POI selected in explorer mode

### ISSUE THREAD

**Issue by sbterito** [teritorio/vido#111]
diff version 1.19 versus 1.21 - bug ?

![compare-explore-mode-V1 19-v1 21](https://github.com/teritorio/vido/assets/57920022/f1c418a2-91f0-49d6-8e8d-548a78780f09)

**Comment by sbterito** [comment]
seems to be a pb with data... none of the hotel in explorer mode

**Comment by frodrigo** [comment]
The issue is about no hotel on the map in explore mode ?

**Comment by frodrigo** [comment]
After tile update it is ok.
