### ISSUE TITLE
[detail] Bad image size

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#127]
http://127.0.0.1:3000/poi/33729/details

http://127.0.0.1:3000/poi/33713/details

![image](https://github.com/teritorio/vido/assets/1785486/d13ccb06-9c30-43a8-bf77-0c68f3c50b71)

**Comment by wazolab** [comment]
@frodrigo : Is this an image ratio issue ? Do we want to fix it to a specific one ? :
- 16:9
- 1:1
- 4:3

**Comment by frodrigo** [comment]
My previous attempt was to fill width and height (I think with "cover" option).

**Comment by wazolab** [comment]
Alright, if we fill width & height and apply object-fit: cover we might have croped images...

More globally, we have to define a frame to ensure a constant layout.

**Comment by wazolab** [comment]
> @frodrigo : Is this an image ratio issue ? Do we want to fix it to a specific one ? :
> 
> * 16:9
> * 1:1
> * 4:3
> 
> An other issue is the ratio of the image served from the API, if we display landscapes images but receive portrait from API, we will have to constraint the portrait within our frame and scale-down the image.
> 
> _Example here of a portrait image (I greyed the background of our landscape frame for a better understanding only) :_
> 
> ![image](https://private-user-images.githubusercontent.com/38253764/328264389-1793837c-37b9-4e12-a30e-2144f72c939a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODc3MTUsIm5iZiI6MTcxNTU4NzQxNSwicGF0aCI6Ii8zODI1Mzc2NC8zMjgyNjQzODktMTc5MzgzN2MtMzdiOS00ZTEyLWEzMGUtMjE0NGY3MmM5MzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwY2RkMmQ3Y2EyNTM5ZjA1ZWM5YzRiNzlmNGQzN2I3NjlkODAyMGI1ZTRmMTcxMmRmN2IwNTgxYjYwODAxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q5DjlsUwKwNhgTkUJ5JjJ28qtgbb1hrSOZHR3e7QPT0)
> 
> Example here of a landscape image :
> 
> ![image](https://private-user-images.githubusercontent.com/38253764/328264065-ba17b381-e43f-437d-b20d-884f79b16326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODc3MTUsIm5iZiI6MTcxNTU4NzQxNSwicGF0aCI6Ii8zODI1Mzc2NC8zMjgyNjQwNjUtYmExN2IzODEtZTQzZi00MzdkLWIyMGQtODg0Zjc5YjE2MzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDFiOGQyMDNmMzNlYmNmNDk2MTM3NTdhOTYyYzI3ZTVkNjVkNWU5MTRhNzY1MDc3YmRkOTE5NmQ2NjM3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BMJY8HGpS_BLDSwvP1tI-fc4Fe2dABoXuCKxPnTu9NM)

Do the solutions I have presented here suit you?

**Comment by frodrigo** [comment]
> Alright, if we fill width & height and apply object-fit: cover we might have croped images...

Yes, it was like this before.
