### ISSUE TITLE
Contrib mode

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#142]
Liste
- show and link to osm contributor
- link to id editor
- show id and link to mapillary

Popup/detail
- link to id editor
- link to add a note https://www.openstreetmap.org/note/new#map=14/45.9531/1.3941&layers=N

Enable/Disabe with URL pram
- save in store/local storage

**Comment by sbterito** [comment]
It is also necessary for organised editing activities to add a link to the notes for the POI concerned. At least initially to OSM.org and at best by giving the choice (on mobile). Feature in popup/detail
cc @frodrigo

**Comment by frodrigo** [comment]
> It is also necessary for organised editing activities to add a link to the notes for the POI concerned. At least initially to OSM.org and at best by giving the choice (on mobile). Feature in popup/detail cc @frodrigo

OSM notes are not associated with OSM objects. Just localized.

**Comment by frodrigo** [comment]
> > OSM notes are not associated with OSM objects. Just localized.
> 
> yep, point then with the precise lat, long (zoom?)

No notes will be there most of the time. I think that bad idea to have a link to nothing most of the time.
