### ISSUE TITLE
Always one star on favorite notebook

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#147]
There is always one star on favourites, nevertheless the number of stars on the main popup.

![image](https://github.com/teritorio/vido/assets/1785486/d3ff3917-f60c-473b-8be5-f7c24790af8a)

**Comment by wazolab** [comment]
Fixed in [9421378](https://github.com/teritorio/vido/commit/94213780f81fe7ea1076a3df6d276ef4ebe70fe0)

**Comment by wazolab** [comment]
It looks like we have a type issue, Stars component expect to have a prop `stars`: number but on FavoriteNoteBook context we have a string which have a length of 1 character.

**Comment by frodrigo** [comment]
> It looks like we have a type issue. `Stars` component expect to have a prop `stars: number` but in `FavoriteNoteBook` context we have a string which have a length of 1 character.

The issue come from the WP API not complying with the spec ? Meanwhile it works outside of the FavoriteNoteBook.

**Comment by wazolab** [comment]
It does work outside of FavoriteNoteBook, I would try to understand why.

**Comment by frodrigo** [comment]
Real issue int the WA API backend, providing stars a string.

**Comment by frodrigo** [comment]
We was wrong. Type of `stars` is `string`.
https://github.com/teritorio/elasa-datasources/blob/master/datasources/schemas/tags/hosting.schema.json#L12

It should be changed in Vido.

**Comment by frodrigo** [comment]
> We was wrong. Type of `stars` is `string`. https://github.com/teritorio/elasa-datasources/blob/master/datasources/schemas/tags/hosting.schema.json#L12
> 
> It should be changed in Vido.

In fact if should be a enum, it does not always contain strictly a number. I'm fixing datasources schema first.

**Comment by frodrigo** [comment]
> > We was wrong. Type of `stars` is `string`. https://github.com/teritorio/elasa-datasources/blob/master/datasources/schemas/tags/hosting.schema.json#L12
> > It should be changed in Vido.
> 
> In fact if should be a enum, it does not always contain strictly a number. I'm fixing datasources schema first.

Done, in datasource. You can ignore the .5 stars, we does not use it. But we have some `nS`. Add a "S" after the stars.

https://wiki.openstreetmap.org/wiki/Key:stars#Hotels
