### ISSUE TITLE
Support any website tag

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#164]
We should support here https://github.com/teritorio/vido/blob/develop/components/Fields/Field.vue#L227

any website tag in form 'website', '.*:website' or 'website:.*' https://taginfo.openstreetmap.org/search?q=website#keys

At the time use the unused https://github.com/teritorio/vido/blob/develop/components/Fields/Website.vue

**Comment by wazolab** [comment]
Do we want to regroup all the *:website:* fields into the same 'website' column, or we keep the control from config ?

**Comment by frodrigo** [comment]
> Do we want to regroup all the _:website:_ fields into the same 'website' column, or we keep the control from config ?

No, each one is a field.

**Comment by wazolab** [comment]
Ok so we have to handle field names translations then, how do we proceed ?
From translations API or I set them in local i18n ?

**Comment by frodrigo** [comment]
Fields are translated from API. Here, you don't even know the name of the field.
