### ISSUE TITLE
From detail to map use link without host name

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#168]
From detail page link to map use link with host name. Should be without host name. Just from root path "/".

Check if there no other place where we can do "relative" link.

**Comment by wazolab** [comment]
@frodrigo : I've applied a fix for relative link, but I'm not sure if it suits all cases ?
What do you think ?
About the other places we could use relative links, I need more informations about which kind of POI can be handled internally and which ones can't
Hotels, for example, have external details pages, but you said that we are moving to make them internal ... do we have other POIs details left as external resources ?
