### ISSUE TITLE
[details] Enable CSS for print in details page

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#18]
Detail page should have a CSS for print.

**Comment by frodrigo** [comment]
https://carte.seignanx.com/poi/8540/details

**Comment by frodrigo** [comment]
- Need better support of images http://localhost:3000/poi/8675/details
![image](https://user-images.githubusercontent.com/1785486/218581966-f7fb6d00-5470-41e3-a15f-787e55f2628a.png)
- Missing waypoint icons (firefox) 
![image](https://user-images.githubusercontent.com/1785486/218582308-52dad558-ec61-44f9-9e20-cc75e9e63ddd.png)
- Use css to avoid content cut http://localhost:3000/poi/8446/details
![image](https://user-images.githubusercontent.com/1785486/218582837-2d8f70c1-c512-480f-9349-bf7f22d09996.png)
![image](https://user-images.githubusercontent.com/1785486/218582948-a599572a-8595-4682-b571-a4fdcea58db1.png)

**Comment by frodrigo** [comment]
@joselegitan please, can you finish the PR on this issue ?

**Comment by joselegitan** [comment]
Update done do no hesitate to tell me if more is needed
