### ISSUE TITLE
gap between POI and icon

### ISSUE THREAD

**Issue by vinber** [teritorio/vido#183]
![image](https://github.com/teritorio/vido/assets/890869/ae35d12d-e680-458b-b1a1-96894c995fec)

https://city-demo-bordeaux.beta.appcarto.teritorio.xyz/5172/#map=20/44.8314951/-0.5980143

**Comment by sbterito** [comment]
Else where
![image](https://github.com/teritorio/vido/assets/57920022/2156bcc9-fb0f-4370-adf9-1d2dc99efa6a)
https://carte.lecoeurdeslandes.com/648/#map=17.79/43.934129/-0.924561

**Comment by frodrigo** [comment]
It is the same for all.

**Comment by wazolab** [comment]
Does this bug is still here ?? I can't reproduce it on my side ... I tried to zoom-in/zoom-out but it's seems to keep the right position.
![image](https://github.com/teritorio/vido/assets/38253764/eb09e772-8c8c-4eaa-8f5d-86d971fc27a3)

**Comment by frodrigo** [comment]
Hum. In fact I was thinking about an other issue

![image](https://github.com/teritorio/vido/assets/1785486/72e176ac-9cd3-4b62-837a-78bd41a4d794)

**Comment by frodrigo** [comment]
> Still there : https://carte.lecoeurdeslandes.com/648/#map=17.79/43.934129/-0.924561 no ? !

No. This one is an other issue. It is a polygon is OSM and the WP API is not so good on making a pont from it.

**Comment by wazolab** [comment]
> Hum. In fact I was thinking about an other issue
> 
> ![image](https://private-user-images.githubusercontent.com/1785486/326793190-72e176ac-9cd3-4b62-837a-78bd41a4d794.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODE3MjgsIm5iZiI6MTcxNDQ4MTQyOCwicGF0aCI6Ii8xNzg1NDg2LzMyNjc5MzE5MC03MmUxNzZhYy05Y2QzLTRiNjItODM3YS03OGJkNDFhNGQ3OTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMTI1MDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjViZmZjOGU2ZDJmMzg4ZTVmOTZmNDUwYzllZDAzOTcwZjZhZWI0MDg4NzE4NGI2MjEyNjAwNTFlNjBmMjYzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XuQ760SCBsociZKBAtnPHH3JdX1-61mJkvxHd2QItho)

So the real issue of this ticket is about the Pin marker being shifted from the POI marker right ?

**Comment by frodrigo** [comment]
> So the real issue of this ticket is about the Pin marker being shifted from the POI marker right ?

No that an other issue. The existing (broken) code is to fix the shifted pin. Not the shifted icon.

**Comment by wazolab** [comment]
After looking, in my opinion, we have an issue on the POI icon not on Red Marker (which is on the right position).
Red Marker or not, the POI icon is shifted sometimes.
In fact it's shifted when we are zoomed-out (when we can see several POIs) and then zoom-in ... at some point during the zooming we are assigning wrongly the coordinates to the Marker.

POI icon shifter with Red Marker (at the right place)
![Screenshot from 2024-05-02 12-36-15](https://github.com/teritorio/vido/assets/38253764/326cec62-c631-4425-bb7f-a6571833cd9c)

Everything ok here
![Screenshot from 2024-05-02 12-36-56](https://github.com/teritorio/vido/assets/38253764/7e66ed1e-a6e8-4049-8e80-a5ddabf91883)

POI icon shifted without Red Marker (if we click on POI Icon, Red Marker will be placed like in the first case, which is ok)
![Screenshot from 2024-05-02 12-37-32](https://github.com/teritorio/vido/assets/38253764/5994b924-a372-47c4-bf9c-9d04c48155cf)
