### ISSUE TITLE
PoisTable export CSV returns GeoJson

### ISSUE THREAD

**Issue by wazolab** [teritorio/vido#200]

**Comment by wazolab** [comment]
@frodrigo do you reproduce the bug on local ? I'm not ...

**Comment by wazolab** [comment]
It looks like API related no ?
- [elasa-dev](https://elasa-dev.teritorio.xyz/api/0.1/granville/tourism/pois/category/18607.csv?geometry_as=point&short_description=false) returns GeoJson obviously...
- [dev.appcarto](https://dev.appcarto.teritorio.xyz/content/api.teritorio/geodata/v0.1/dev/tourism/pois/category/8247.csv?geometry_as=point&short_description=false) returns a csv

**Comment by frodrigo** [comment]
Ok, not yet implement in the Elasa API.
