### ISSUE TITLE
[list] Pagination is not translated

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#205]
On develop branch the pagination translation is missing

**Comment by wazolab** [comment]
It looks ok to me ...

EN: ![Screenshot from 2024-03-20 09-00-33](https://github.com/teritorio/vido/assets/38253764/84d2ec02-4208-4a4d-82c4-35a520690269)


FR: ![Screenshot from 2024-03-20 09-00-15](https://github.com/teritorio/vido/assets/38253764/75a34c22-3555-47b6-94a9-a6152ac69681)

ES: ![Screenshot from 2024-03-20 09-00-24](https://github.com/teritorio/vido/assets/38253764/6ddb0fe9-409c-494b-9fc7-cf04dc28734c)

Can you provide more details about your bug please ?

**Comment by frodrigo** [comment]
On initial load (in french) without change the language, the pagination is in english.

**Comment by wazolab** [comment]
It's because we never get the user system locale, thus the default is english until the user changes it.
Do you want to collect user's system locale and set it as default ?

**Comment by frodrigo** [comment]
On my side it already use the use locale for other parts of the page.

**Comment by wazolab** [comment]
Yep after going deeper in my conf I can reproduce the behavior you are talking about :)
I think I have to set vuetify's locale on inital load instead of using the fallback directly.
