### ISSUE TITLE
[list] Switching from small layout to large layout reload the full page

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#208]
Switching from small layout to large layout reload the full page

**Comment by wazolab** [comment]
What do you mean by switching ? resizing the browser window ? toggeling device mode ?

**Comment by frodrigo** [comment]
![Peek 20-03-2024 11-47](https://github.com/teritorio/vido/assets/1785486/320ef188-ba7a-4168-a576-bd3799e15541)

**Comment by wazolab** [comment]
Maybe the page reload is triggered by a Browser setting on your side ? I can't reproduce on my side ...
Which browser are you using ?

**Comment by frodrigo** [comment]
> Which browser are you using ?

Firefox

**Comment by wazolab** [comment]
I confirm there is an option to reload when user-agent is changed
![image](https://github.com/teritorio/vido/assets/38253764/8b58d934-8057-4707-b973-c7d9bce82250)

**Comment by frodrigo** [comment]
Ok. I does not found this option on my Firefox. But yes, in my case it looks linked to "touch simulation toggled"
