### ISSUE TITLE
[list] Lost of load in progress

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#211]
Before we have a load in progress image. But now it is missing.

Can we easily get it again ?

**Comment by wazolab** [comment]
You mean the loading state of the Table ? During data fetching ?

**Comment by frodrigo** [comment]
Yes

**Comment by wazolab** [comment]
This task is a bit more complex than I though, it looks like we have a reactivity issue that I can't figure for the moment ...

**Comment by wazolab** [comment]
TODO: At least we could empty the list during data fetching.
