### ISSUE TITLE
/sitemap.xml fails with http 500

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#218]
/sitemap.xml fails with http 500

**Comment by wazolab** [comment]
![image](https://github.com/teritorio/vido/assets/38253764/3c66bd75-60bf-4487-ab4f-c9d76f99adf5)

Good on my side but very long ... from were do you have this 500 ? From Google Search Console ?
I think Google Bot might leave our Sitemap before it loads as it's too long.
So we might need to improve the overall page loading time for sure.

**Comment by frodrigo** [comment]
Tested on dev serveur. Load time issue come from the backend API.

**Comment by frodrigo** [comment]
On production it go to cache.

**Comment by frodrigo** [comment]
Ok for too on dev instance
