### ISSUE TITLE
Inconsistency with trailing slashes on URLs

### ISSUE THREAD

**Issue by wazolab** [teritorio/vido#253]
Both URLs should display the same:
- https://cartelandes.com/category/embedded/45911/?menuItemIds=45911 (infinite loading)
- https://cartelandes.com/category/embedded/45911?menuItemIds=45911

**Comment by frodrigo** [comment]
We can close this ?

Note cartelandes.com is not at `develop`.

**Comment by wazolab** [comment]
I think yes, I can't find any issue for the moment ...
