### ISSUE TITLE
[list] Selector menu width jump

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#258]
On detail page list, on full page only and not in the embedded one, the width of the category selector width is changing while scrolling the content.

![Peek 10-04-2024 10-26](https://github.com/teritorio/vido/assets/1785486/e9a05dfc-bb47-4309-bee4-7065ed1cf158)

**Comment by wazolab** [comment]
Should we keep the width the same as the selector's width ?
Which is the case on embedded page as it's 100% wide.

**Comment by frodrigo** [comment]
Yes.

**Comment by wazolab** [comment]
Alright but we will have category name 'ellipsed', is this acceptable ?
![image](https://github.com/teritorio/vido/assets/38253764/1e8ca71f-9cc4-4edd-b5c1-194d776ededc)
