### ISSUE TITLE
Add LinkedIn support

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#268]

**Comment by wazolab** [comment]
For the moment I've added Linkedin support on Share component only.
![image](https://github.com/teritorio/vido/assets/38253764/41bb948e-2d4c-4590-9520-df58a18e8916)

I am wondering if I need to add it to Field too ? Does the API provides Linkedin links ?
Would displays a Linkedin column on List page as follows:
![image](https://github.com/teritorio/vido/assets/38253764/1b42ab15-c4cb-49f8-8442-adbe21dcca0a)

Am I forgetting a place where to add linkedin support ?
