### ISSUE TITLE
Special character not interpreted in Popup

### ISSUE THREAD

**Issue by wazolab** [teritorio/vido#301]
![image](https://github.com/teritorio/vido/assets/38253764/fbaca963-e3da-43e1-b578-8f1eae38fe78)

**Comment by frodrigo** [comment]
Do you have a link or the returned content from the API ?

**Comment by vinber** [comment]
this https://cartinfo.cocm.fr/196/4173

**Comment by frodrigo** [comment]
That an API issue

On short description should be test only

https://cartinfo.cocm.fr/content/api.teritorio/geodata/v0.1/cocm/tourism/pois/category/196.geojson?geometry_as=point&short_description=true

**Comment by wazolab** [comment]
So we close this issue ?
