### ISSUE TITLE
no pop-up in explore mod

### ISSUE THREAD

**Issue by vinber** [teritorio/vido#321]
https://wp.beta.appcarto.teritorio.xyz/#map=20/44.2090494/-1.2959788&mode=explorer there's no pop-up

Pop-up are ok in normal mod https://wp.beta.appcarto.teritorio.xyz/196/504303

**Comment by wazolab** [comment]
It looks like the POI you tried isn't configured to have this popup in Explorer mode.
It's the same for the rest of POIs in Landes teritoryon Dev instance.
We can close this issue as I've tested the feature with proper config and it's working.
cc @frodrigo
