### ISSUE TITLE
[Popup] - Add close button

### ISSUE THREAD

**Issue by wazolab** [teritorio/vido#328]
Add close button on top right in order to have an explicit interaction (instead of clicking somewhere in the map to close popup)
![image](https://github.com/teritorio/vido/assets/38253764/1bc7182f-1761-43d1-a2eb-e7348dd02050)

Thus it will clarify the purpose of "Menu" button in the background, which can be misleading fo the user.

**Comment by frodrigo** [comment]
> Add close button on top right

And remove the [menu] box ?
