### ISSUE TITLE
[detail] Add the category name into the page title 

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#350]
Add the category name into the page title (h1) and `<header><title>`.

"[Catrgory name] - [POI name]"

**Comment by wazolab** [comment]
In which do we have to apply this ?
Homepage ? List Page ? Details
how do we manage multiple categories selection on Homepage, do we add them all ?

**Comment by frodrigo** [comment]
As written in the issue title, this issue is for detail pages.

**Comment by wazolab** [comment]
my bad
