### ISSUE TITLE
Show isochrone on map from POICard

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#359]
Add a button to POICard
- [x] once clicked ask for transportation mode (foot, bike, car)
- [x] call a Isochrone OpenRouteService API, can take time, maybe with a waiting UX.
- [x] add the polygon to the map
- [x] once POI unselected, remove the polygon
- [x] display distance and range_type on isochrone border + color fill
- [x] fetch 3 range (15min, 30min, 1h) within 1 API call
- [x] The isochron button should be an instance option (`isochroneEnabled: boolean`)

Wording should be chosen

**Comment by wazolab** [comment]
We have several options about Isochrone API, I've tried to keep only the open-source and free one's:
- [OpenRouteService](https://openrouteservice.org)
  - Has [JavaScript SDK](https://github.com/GIScience/openrouteservice-js)
  - Has a lot of profiles (car, bicycle, pedestrian, wheelchair)
- [GeoService Isochrone API](https://geoservices.ign.fr/documentation/services/api-et-services-ogc/isochrone/api)
  - only for car or pedestrian
  - :warning: looks deprecated as it is under "Services Dépréciés"

**Comment by wazolab** [comment]
**Exemples of UI**
- https://commutetimemap.com/map
- https://docs.mapbox.com/playground/isochrone/

**Comment by frodrigo** [comment]
We need something very simple : just selection of the transport mode.

**Comment by wazolab** [comment]
Sure, it's just to keep those ideas ;)

**Comment by wazolab** [comment]
## Feedback
- border same color as fill
- text-halo-width: 2 (test with same color as border)
- Get lighter color
- Try with one layer and use conditional expression
- Icon + text on profile button
- Maybe remove Calculate button (API on profile selection)
- Improve profile button design
- Center map on bbox
- display isochrone polygon under line / text
