### ISSUE TITLE
Add an URL param to filter the content by polygon

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#376]
There is already alternatives boundaries polygon param. Add an other param to enable POI filtering by the poly.
The param should be forwarded to the API. The API will return the filtered content.

**Comment by wazolab** [comment]
Pass query param here: https://github.com/teritorio/vido/blob/c05a4ea68f0022be16c7196fcb2c6170d9bc8cb2/stores/menu.ts#L178

**Comment by frodrigo** [comment]
Paramter cliping_polygon_slug

**Comment by wazolab** [comment]
Should I test if the slug is present in `settings.polygon_extra` ? Or could it be any polygon slug the API can understand (meaning outside of the current settings ?)

**Comment by frodrigo** [comment]
> Should I test if the slug is present in `settings.polygon_extra` ?

No
