### ISSUE TITLE
Boundry multipolygon not show

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#383]
When the boundary poly is a multipoly all is gray.

**Comment by wazolab** [comment]
[MapBase.vue L. 295](https://github.com/teritorio/vido/blob/2b6d7023ff82944c790ee86426213f907ffaa239/components/Map/MapBase.vue#L307)

**Comment by wazolab** [comment]
I've tried with MultiPolygon from ['mont-de-marsan-agglomeration'](https://dev.appcarto.teritorio.xyz/content/api.teritorio/geodata/v0.1/dev/tourism/poi/25639.geojson)

Everything seems ok to me :
![image](https://github.com/user-attachments/assets/0305ef8e-9273-4763-a0cc-b358ba4b98dc)

**Comment by frodrigo** [comment]
> ['mont-de-marsan-agglomeration'](https://dev.appcarto.teritorio.xyz/content/api.teritorio/geodata/v0.1/dev/tourism/poi/25639.geojson)

That not a multipolygon.

Here the default poly is a multipoly

https://carto.kestolog.com
https://carto.kestolog.com/api/0.1/kestolog/logistic/settings.json
