### ISSUE TITLE
scroll bar for content, not for the pop-up

### ISSUE THREAD

**Issue by vinber** [teritorio/vido#39]
i think it's better to have a scroll bar for the content of the pop-up, not for the entire pop popup -> we lose buttons when content is long 

![image](https://user-images.githubusercontent.com/890869/210582436-ea139bf8-1c0b-4168-90f9-59e6cbd7e9e6.png)

![image](https://user-images.githubusercontent.com/890869/210582536-d501b50f-8db3-4945-a152-828a4a2898c5.png)

**Comment by frodrigo** [comment]
No. We already do this and reverted.
