### ISSUE TITLE
Upgrade to Nuxt 3 / Vue 3

### ISSUE THREAD

**Issue by GuillaumeAmat** [teritorio/vido#4]
Hey there :wave: 

Just to let you know that Nuxt 3 will hopefully be released later this year or early 2023. In any case, you should plan to upgrade Vido to Nuxt 3 in 2023.

**Why is that?**

Because Vido is based on _Nuxt 2_ as of today, which means that you also use _Vue 2_, for which the _End Of Life_ is planned to late 2023.

Upgrading to Nuxt 3 will bring you Vue 3 as well :ok_hand:

**Comment by frodrigo** [comment]
Have to remove `vue-tailwind`. It will not be ported to Vue 3.
- The same author started a replacement project `https://github.com/variantjs/vue`. Maybe already a dead project.
- Use an alternative lib

**Comment by frodrigo** [comment]
|                                   | Vue-tailwind | flowbite   | Vuetify     | Element Plus    |
| --------------------------------- | ------------ | ---------- | ----------- | --------------- |
| github                            | dead         | 4k, stable | 36k, stable | 18k, slows down |
| tailwind                          | x            | x          | \-          | \-              |
| Vue/Nuxt                          | v2           | v3         | V2/3        | V3              |
| Modal / Dialog                    | x            | x          | x           | x               |
| Dropdown / Menu                   | x            | x          | x           | x               |
| RichSelect                        | x            | ~          | x           | ~               |
| Dual Number range slider / slider | \-           | \-         | x           | x               |
| Image slide show                  | \-           | \-         | \-          | \-              |
| Toast                             | \-           | x          | \-          | \-              |
| Data Table                        | \-           | x          | x           | x               |
| Date picker                       | \-           | x          | ?           | x               |

Let try with vuetify.

**Comment by sbterito** [comment]
It's done isn't it @frodrigo ?
