### ISSUE TITLE
Detail icon cut on detail block

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#415]
The background icon is cut

![image](https://github.com/user-attachments/assets/1f130ee1-ec62-404d-ab57-0e82ce86616c)

**Comment by wazolab** [comment]
@frodrigo do you know which config can provide such details rendering on Local ? Either from Elasa or WP ?

**Comment by frodrigo** [comment]
WP, That a Prod issue

https://carte.seignanx.com/poi/27213/details
