### ISSUE TITLE
Cannot interact with the map on the left of the PoiCard

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#56]
Cannot interact with the map on the left of the PoiCard

![Peek 01-02-2023 18-33](https://user-images.githubusercontent.com/1785486/216119233-44970934-9db7-4999-8d9d-54fadc298e74.gif)

**Comment by vinber** [comment]
sorry for duplicate, it's left and right (except under right vertical menu)

**Comment by frodrigo** [comment]
Done on dev, cherry-picked on main

**Comment by vinber** [comment]
> cherry-picked on main

i don't understand :(
