### ISSUE TITLE
Deps POIs order does not reflect the choice in BO

### ISSUE THREAD

**Issue by sbterito** [teritorio/vido#72]
Choice in BO
![image](https://user-images.githubusercontent.com/57920022/224564702-0d56384e-d564-4186-a2b9-0c3d1881dc7c.png)

Result in FO
![image](https://user-images.githubusercontent.com/57920022/224564729-3c035d08-35d6-4703-972b-a79ba3f3ff8a.png)

**Comment by wazolab** [comment]
Ex: https://carte.seignanx.com/poi/10269/details#map=11.3/43.5519/-1.4448

**Comment by wazolab** [comment]
@frodrigo If I take the example of this URL : https://carte.seignanx.com/poi/24675/details
The order we display POIs is the same as what the API returns :face_with_diagonal_mouth: 
Maybe the issue comes from the fact that Frontend of BO shows a different order than the API response ?

**Comment by frodrigo** [comment]
> The order we display POIs is the same as what the API returns 🫤
Maybe the issue comes from the fact that Frontend of BO shows a different order than the API response ?

@abdechakour please, can you check this ?

**Comment by abdechakour** [comment]
The problem is that when we pass poi_ids to where clause for selecting from database we lose the sort
I will do a PR to fix this
