### ISSUE TITLE
Paragraphs or spaces between blocks of text entered in BO are not interpreted

### ISSUE THREAD

**Issue by sbterito** [teritorio/vido#73]
BO
![image](https://user-images.githubusercontent.com/57920022/224619486-46c30ee3-ff79-4b09-80b0-55a579c4ad4b.png)

FO
![image](https://user-images.githubusercontent.com/57920022/224619664-f62ffcda-e730-4ab6-8b5b-60d66d4634b0.png)

**Comment by wazolab** [comment]
@frodrigo @sbterito : Can you provide an URL / Example please ?

**Comment by sbterito** [comment]
@wazolab 

it's edited this way via the WP back office

![image](https://github.com/teritorio/vido/assets/57920022/e45607db-7fbc-4dd7-be9c-19cff092b9ce)


 here's how wp interprets it https://carte.seignanx.com/content/parcours-plus/saint-jacques-de-compostelle/
 You need to see the html code returned by WP.

here's how vido interprets it : https://carte.seignanx.com/poi/10269/details#map=12.12/43.55186/-1.42043

**Comment by frodrigo** [comment]
https://carte.seignanx.com/content/api.teritorio/geodata/v0.1/a/b/poi/10269.geojson

**Comment by wazolab** [comment]
@frodrigo the description received from the API looks "partially" escaped ... `<p>` tag and `<br>` are removed but not `<a>`.
Do you apply some kind of html tag sanitize on API side ?
I'm afraid I can't do much if I don't receive structured data as we are already rendering `description` through `v-html` directive (which interprets html tags).

In the example case everything works fine as the `<a>` tag i properly rendered and present in the API response.

**Comment by frodrigo** [comment]
OK. So as it an API issue. I close this issue.
