### ISSUE TITLE
Sort filter content

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#75]
Sort filter content after translation.

The content is in API order, but after translation should be sorted in current language.

**Comment by wazolab** [comment]
Are we talking about options within CategorySelector ?
![image](https://github.com/teritorio/vido/assets/38253764/dac53d7d-4b14-4502-911a-2c3f77c8d80c)

**Comment by frodrigo** [comment]
No, the filter for POI on main menu.

![image](https://github.com/teritorio/vido/assets/1785486/2081a2b2-9c49-4105-96c4-6d0cd35c252a)

**Comment by wazolab** [comment]
Does the select's options are supposed to be translated already ?

Because it looks that it's not the case for the moment (app is in Spanish) :
![image](https://github.com/teritorio/vido/assets/38253764/10dc31b4-4d3b-4318-9789-b9b765fa9019)

**Comment by frodrigo** [comment]
Any language could be available, but yes, for now only FR is available with the current API.
