### ISSUE TITLE
[detail] Horizontal scroll on mobile

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#83]
Details pages has an horizontality scroll on mobile device (as least mine, android) with Chrome and Firefox.

But there is no scroll on desktop browser (Chrome and Firefox) using large or small responsive layout.

**Comment by AdnaneAm** [comment]
Can't reproduce the issue, tried different screen sizes and mobiles views but couldn't get the horizontal scrollbar.

Could you please provide me with your phone model so I can test in on that specific device ?
![image](https://github.com/teritorio/vido/assets/18250524/b4d8fdae-6afa-46e8-bdea-c1ca2e83220d)

**Comment by AdnaneAm** [comment]
![image](https://github.com/teritorio/vido/assets/18250524/51368844-fa00-4c91-af3e-6d58aa720cb3)
I've used Browserstack to reproduce the issue on a real Oneplus 8P device but couldn't reproduce it, if you would take a screenshot of the issue so I can have a better idea how it looks.
