### ISSUE TITLE
Filter range - include bound values

### ISSUE THREAD

**Issue by frodrigo** [teritorio/vido#91]
Bound values are excluded from filter.

Allow bounds value as selected by the filter.

**Comment by AdnaneAm** [comment]
I've checked the values sent by number range filters and they seem to include the bound values. So can't seem to reproduce the issue

**Comment by frodrigo** [comment]
I recheck and confirm the issue.

https://dev2.appcarto.teritorio.xyz/32373/511399#map=10.63/43.8735/-0.3475

The route is 3h = 180min long.
With with time filter to 180 is no more displayed.

**Comment by AdnaneAm** [comment]
Yes thanks for your help, I was able to reproduce the issue.
